disabled-worlds:
  - example_world
  - custom_world_name

# players.<uuid>.xp will be created automatically when you add/remove xp with commands
players: {}

#used for animated Displays
tick-speed: 10

levels:
  1:
    display:
      - "&aLevel 1 - &7Beginner"
      - "&cLevel 1 - &7Beginner"
      - "&4Level 1 - &7Beginner"
  2:
    display: "&bLevel 2 - &7Novice"
  3:
    display: "&6Level 3 - &7Intermediate"

# XP formula (used if no per-level xp overrides)
formula:
  base: 100
  multiplier: 2.0