disabled-worlds:
  - example_world

# players.<uuid>.xp and rewarded-levels are created automatically
players: {}

# Used for animated displays (ticks)
tick-speed: 10

levels:
  1:
    display:
      - "&aLevel 1 - &7Beginner"
      - "&cLevel 1 - &7Beginner"
      - "&4Level 1 - &7Beginner"
    reward:
      type: command
      commands:
        - "eco give %player_name% 10"
  2:
    display: "&bLevel 2 - &7Novice"
    reward:
      type: message
      messages:
        - "&aYou have just reached &eLevel 2&a!"
    permission: "simplelevels.level.2"
  3:
    display:
      - "&6Level 3 - &7Intermediate"
      - "&eLevel 3 - &7Intermediate"
    reward:
      type: command
      commands:
        - "eco give %player_name% 50"
        - "say %player_name% reached Level 3!"
    permission: "simplelevels.level.3"
   #xp: 10000

# XP formula (used if no per-level XP override exists)
formula:
  base: 100
  multiplier: 2.0