disabled-worlds:
  - world_nether
  - world_the_end

# players.<uuid>.xp will be created automatically when you give/remove xp with commands
players: {}

# optional per-level entries:
levels:
  1:
    display: "&aLevel 1 - &7Beginner"
    # xp: 50   # optional: set a specific XP required for level 1
  2:
    display: "&bLevel 2 - &7Novice"
  3:
    display: "&6Level 3 - &7Intermediate"

# XP formula (used if no per-level xp overrides)
formula:
  base: 100
  multiplier: 2.0