name: LevelSystem
main: de.nitrox.levelsystem.LevelSystem
version: 1.2
api-version: 1.20
description: Multi-LevelSystem plugin
author: Nitrox_XD

commands:
  addxp:
    description: Add XP to a player in a specific system
    usage: "/addxp <system> <amount> <player>"
    permission: levelsystem.addxp
  removexp:
    description: Remove XP from a player in a specific system
    usage: "/removexp <system> <amount> <player>"
    permission: levelsystem.removexp
  reloadlevelsystem:
    description: Reload all LevelSystem configs
    usage: "/reloadlevelsystem"
    permission: levelsystem.reload
  levelstats:
    description: Show your stats for a specific levelsystem
    usage: "/levelstats <identifier> <player>"

permissions:
  levelsystem.addxp:
    description: Allows adding XP
    default: op
  levelsystem.removexp:
    description: Allows removing XP
    default: op
  levelsystem.reload:
    description: Allows reloading systems
    default: op
