name: SimpleLevels
main: de.nitrox.levelsystem.LevelSystem
version: 1.3
api-version: 1.20
description: Multi-LevelSystem plugin
author: Nitrox_XD

commands:
  simplelevels:
    description: Main command for the SimpleLevels plugin
    usage: /simplelevels <subcommand>
    aliases: [sl]

permissions:
  simplelevels.addxp:
    description: Allows adding XP
    default: op

  simplelevels.removexp:
    description: Allows removing XP
    default: op

  simplelevels.reload:
    description: Allows reloading the plugin
    default: op